# NumPy Reference Page

***

### NumPy Arrays

In [1]:
import numpy as np
from functools import partial

# Define special version of print for better array printing
xprint = partial(print, end='\n\n')

In [2]:
list = [1,2,3]
xprint(list)
xprint(np.array(list))

[1, 2, 3]

[1 2 3]



In [3]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
xprint(matrix)
xprint(np.array(matrix))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]



In [4]:
xprint(np.arange(10))
xprint(np.arange(0,10,2))

[0 1 2 3 4 5 6 7 8 9]

[0 2 4 6 8]



In [5]:
xprint(np.zeros(3))

# Note how you have to pass in as a tuple
xprint(np.zeros((4,3)))
xprint(np.ones(6))

# And again here
xprint(np.ones((5,5)))

[0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[1. 1. 1. 1. 1. 1.]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]



In [6]:
# Linearly spaced over 5 points in range of 0 to 10
xprint(np.linspace(0,10,5))

[ 0.   2.5  5.   7.5 10. ]



In [7]:
# Identity Matrix
xprint(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



In [8]:
xprint(np.random.rand(5))
xprint(np.random.rand(3,3))

# Random numbers for normal distribution
xprint(np.random.rand(3,3))

# Get random ints, note that specified highest num is not inclusive
xprint(np.random.randint(1,100,10))

[0.02011101 0.3354408  0.76575995 0.98411302 0.07786231]

[[0.91594145 0.93410242 0.44237773]
 [0.66654626 0.39494832 0.75629915]
 [0.49900761 0.91670735 0.13802524]]

[[0.30472321 0.03172702 0.8674701 ]
 [0.64417903 0.04879096 0.81331413]
 [0.48365525 0.93439609 0.12558409]]

[87 78  6 42 43 16 25 26 92 51]



In [9]:
xprint(np.arange(0,25))

# Reshaping
xprint(np.arange(0,25).reshape(5,5))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]



Retrieving data from NumPy arrays

In [10]:
test_array = np.random.randint(0,100,10)
xprint(test_array)

# Max value and index
xprint(test_array.max())
xprint(test_array.argmax())

# Min value and index
xprint(test_array.min())
xprint(test_array.argmin())

# Shape
xprint(test_array.shape)

# Return type of data in array
xprint(test_array.dtype)

[51 89 97 55 79 20  3 62 67 75]

97

2

3

6

(10,)

int64



### NumPy Indexing and Selection

Pretty similar to the way Python lists work

In [11]:
xprint(test_array[1:4])

[89 97 55]



Pay careful attention modifying arrays, as manipulations often modify the original copy

In [12]:
foo = np.arange(0,100,5)
xprint(foo)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]



In [13]:
slice = foo[2:10]
slice[:] = 17
print('This is slice:')
xprint(slice)
print('This is foo:')
xprint(foo)

This is slice:
[17 17 17 17 17 17 17 17]

This is foo:
[ 0  5 17 17 17 17 17 17 17 17 50 55 60 65 70 75 80 85 90 95]



To avoid this, you can make a copy like so

In [14]:
copy = foo.copy()
copy[:] = 1
print('This is copy:')
xprint(copy)
print('This is foo, which has remained unaffected:')
xprint(foo)

This is copy:
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]

This is foo, which has remained unaffected:
[ 0  5 17 17 17 17 17 17 17 17 50 55 60 65 70 75 80 85 90 95]



In [15]:
twoD = np.array([[5,10,15],[20,25,30],[35,40,45]])
xprint(twoD)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]



In [16]:
xprint(twoD[2])
xprint(twoD[2][2])
xprint(twoD[2][1:])

[35 40 45]

45

[40 45]



In [17]:
somearray = np.arange(1,11)
xprint(somearray)
boolArr = somearray > 5
xprint(boolArr)
xprint(somearray[boolArr])
xprint(somearray[somearray > 5])

[ 1  2  3  4  5  6  7  8  9 10]

[False False False False False  True  True  True  True  True]

[ 6  7  8  9 10]

[ 6  7  8  9 10]



### NumPy Operations

In [18]:
bar = np.arange(1,11)
xprint(bar)

[ 1  2  3  4  5  6  7  8  9 10]



In [19]:
xprint(bar * 100)
xprint(bar + bar)
xprint(bar * bar)
xprint(bar - bar)
xprint(bar / bar)
xprint(bar % bar)
xprint(bar ** bar)
xprint(np.sqrt(bar))
xprint(np.sin(bar))
xprint(np.cos(bar))
xprint(np.tan(bar))
xprint(np.log(bar))

# Doesn't affect original
print('Original: ')
xprint(bar)

[ 100  200  300  400  500  600  700  800  900 1000]

[ 2  4  6  8 10 12 14 16 18 20]

[  1   4   9  16  25  36  49  64  81 100]

[0 0 0 0 0 0 0 0 0 0]

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

[0 0 0 0 0 0 0 0 0 0]

[          1           4          27         256        3125       46656
      823543    16777216   387420489 10000000000]

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111]

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026 -0.83907153]

[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501 -0.29100619
  0.87144798 -6.79971146 -0.45231566  0.64836083]

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]

Original: 
[ 1  2  3  4  5  6  7  8  9 10]



Note that dividing zero by zero in NumPy gives you nan, and dividing any number != zero gives you inf

In [20]:
xprint(np.zeros(5)/np.zeros(5))

[nan nan nan nan nan]



/home/kevin/env/jupyterML/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [21]:
xprint(np.ones(5)/np.zeros(5))

[inf inf inf inf inf]



/home/kevin/env/jupyterML/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
