# NumPy Reference Page

In [1]:
import numpy as np
from functools import partial

# Define special version of print for better array printing
xprint = partial(print, end='\n\n')

In [2]:
list = [1,2,3]
xprint(list)
xprint(np.array(list))

[1, 2, 3]

[1 2 3]



In [3]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
xprint(matrix)
xprint(np.array(matrix))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]



In [4]:
xprint(np.arange(10))
xprint(np.arange(0,10,2))

[0 1 2 3 4 5 6 7 8 9]

[0 2 4 6 8]



In [5]:
xprint(np.zeros(3))

# Note how you have to pass in as a tuple
xprint(np.zeros((4,3)))
xprint(np.ones(6))

# And again here
xprint(np.ones((5,5)))

[0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[1. 1. 1. 1. 1. 1.]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]



In [6]:
# Linearly spaced over 5 points in range of 0 to 10
xprint(np.linspace(0,10,5))

[ 0.   2.5  5.   7.5 10. ]



In [7]:
# Identity Matrix
xprint(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



In [8]:
xprint(np.random.rand(5))
xprint(np.random.rand(3,3))

# Random numbers for normal distribution
xprint(np.random.rand(3,3))

# Get random ints
xprint(np.random.randint(1,100,10))

[0.55867879 0.58985155 0.9532458  0.51167906 0.8840176 ]

[[0.80277357 0.11061871 0.9287045 ]
 [0.79784953 0.5567325  0.07702903]
 [0.6340223  0.34370284 0.22846382]]

[[0.53319406 0.75151427 0.72410465]
 [0.18725381 0.05896967 0.89762335]
 [0.6987869  0.46599706 0.24967081]]

[22 92 24 96 65 72 49 80 65 85]

